# render.yaml (Версия 5 - Диск ВНУТРИ сервиса, синтаксис по документации)

services:
  - type: web
    name: telegram-story-bot # Имя сервиса
    env: python
    plan: free
    region: frankfurt # Опционально: можно указать регион (напр., ближе к вам или Telegram)
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Устанавливать через UI
      - key: GEMINI_API_KEY
        sync: false # Устанавливать через UI
      - key: DATA_FILE_PATH # Путь к БД, использующий mountPath диска
        value: /var/data/bot_data.db
      - key: LOG_LEVEL
        value: INFO
    autoDeploy: yes # Включить авторазвертывание из Git
    # --- Определение диска ВНУТРИ сервиса ---
    # Используем единственное число 'disk' и свойства из документации
    disk:
      name: data          # Имя диска (должно быть уникальным для Blueprint)
      mountPath: /var/data # Куда монтировать в контейнере
      sizeGB: 1          # Размер (1 ГБ бесплатно)