# render.yaml (Версия 4 - Упрощенная привязка диска)

# Определяем диски на самом верхнем уровне
disks:
  - name: data          # Имя диска (важно, чтобы оно было уникальным)
    mountPath: /var/data # Точка монтирования в контейнере
    sizeGB: 1          # Размер (1 ГБ бесплатно)

# Определяем сервисы
services:
  - type: web
    name: telegram-story-bot # Имя сервиса
    env: python
    plan: free
    region: frankfurt # Опционально
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DATA_FILE_PATH # Путь к БД, совпадающий с mountPath диска
        value: /var/data/bot_data.db # Render должен автоматически использовать диск 'data'
      - key: LOG_LEVEL
        value: INFO
    autoDeploy: yes
    # --- Явная секция disk: УБРАНА ---
    # Render должен сам связать диск по совпадающему mountPath