# render.yaml (Исправленная версия)

# --- Блок disks теперь на верхнем уровне ---
disks:
  - name: data # Имя диска
    mountPath: /var/data # Точка монтирования диска
    sizeGB: 1 # Минимальный размер (1 ГБ бесплатно)

services:
  - type: web # Используем тип 'web'
    name: telegram-story-bot # Имя вашего сервиса на Render
    env: python # Указываем окружение Python
    plan: free # Используем бесплатный тариф
    buildCommand: "pip install -r requirements.txt" # Команда для установки зависимостей
    startCommand: "bash start.sh" # Команда для запуска вашего бота
    envVars:
      - key: PYTHON_VERSION # Указываем желаемую версию Python
        value: 3.11 # Или 3.10, 3.12
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Не синхронизировать из YAML, устанавливать через UI Render
      - key: GEMINI_API_KEY
        sync: false # Не синхронизировать из YAML, устанавливать через UI Render
      - key: DATA_FILE_PATH # Путь к БД на персистентном диске Render
        value: /var/data/bot_data.db # Используем путь из определения диска выше
      - key: LOG_LEVEL # Можно переопределить уровень логов для продакшена
        value: INFO # Или DEBUG
    healthCheckPath: / # Путь для health check запросов
    # --- Блок disks УБРАН отсюда ---
    autoDeploy: yes # Автоматически развертывать при изменениях в репозитории