# render.yaml (Версия 3 - Гарантированно верхний уровень)

# Определяем диски на самом верхнем уровне
disks:
  - name: data          # Имя для ссылки на диск
    mountPath: /var/data # Куда монтировать в контейнере
    sizeGB: 1          # Размер (1 ГБ бесплатно)

# Определяем сервисы после всех объявлений верхнего уровня
services:
  - type: web
    name: telegram-story-bot # Имя сервиса
    env: python
    plan: free
    region: frankfurt # Опционально: можно указать регион (напр., ближе к вам или Telegram)
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Устанавливать через UI
      - key: GEMINI_API_KEY
        sync: false # Устанавливать через UI
      - key: DATA_FILE_PATH # Путь к БД, использующий mountPath диска
        value: /var/data/bot_data.db
      - key: LOG_LEVEL
        value: INFO
    autoDeploy: yes # Включить авторазвертывание из Git
    # --- Ссылка на ранее определенный диск ---
    # Указываем, какой диск использовать для этого сервиса
    disk:
      name: data # Имя диска, определенное выше
      mountPath: /var/data # Точка монтирования (должна совпадать)